local GuardianAttack = dofile("src/server/GuardianAttack.lua")
local attack = GuardianAttack.new()
assert(not attack:Resolve(), "Idle attacks cannot damage")
assert(not attack:Interrupt(0, 8), "Idle strikes cannot spend an interrupt")
assert(attack:Begin())
assert(not attack:Begin(), "Repeated begin cannot reset a wind-up")
assert(not attack:Interrupt(0, nil), "Other characters cannot interrupt")
assert(attack:Interrupt(0, 8), "First interrupt succeeds")
assert(not attack:Interrupt(1, 8), "An attack can only be interrupted once")
assert(not attack:Resolve(), "Interrupted attack cannot damage")
assert(not attack:Resolve(), "No duplicate damage resolution")
assert(attack:Begin())
assert(not attack:Interrupt(7.99, 8), "Cooldown persists across attacks")
assert(attack:Resolve(), "Normal attack can damage")
assert(attack:Begin())
assert(attack:Interrupt(8, 8), "Cooldown is available at exact deadline")
assert(not attack:Resolve())
local other = GuardianAttack.new()
assert(other:Begin() and other:Interrupt(1, 8), "Guardians have independent cooldowns")
print("Guardian attack regression tests passed")
